APP:
  NAME: MyApp
  RUNMODE: debug # 模式: debug, release, gotest
  Addr: :8080 # 端口
  URL: http://localhost:8080 # 网站 url，内部跳转时会用到该项

DB:
  HOST: 127.0.0.1
  PORT: 3306
  DATABASE: blog
  USERNAME: root
  PASSWORD: root